const express = require('express')
const app = express()
app.use('/static', express.static('dist'))
app.use(express.static('test/static'))
app.set('port', process.env.PORT || 3000)
app.listen(app.get('port'), () => console.log(`Listening on port ${app.get('port')}!`))
